{
 "title": "Packet Spot Prices",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "plan",
    "query": "label_values(packet_spot_market_price, plan)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrapes  per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(packet_spot_market_price_scrapes_total[10m]) * 60",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(packet_spot_market_price_query_failures[10m]) * 60",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Query Time per Scrape",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(packet_spot_market_price_query_duration_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "repeat": "plan",
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  },
  {
   "title": "$plan - Price by facility",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "packet_spot_market_price{plan=~\"^($plan)$\"}",
     "legendFormat": "{{facility}} "
    }
   ]
  }
 ]
}